#!/usr/bin/env python3
# -*- coding: utf-8 -*-


# -- General configuration ------------------------------------------------


# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'Dokumenty na úřední desce'
copyright = '2017, Michal Škop'
author = 'Michal Škop'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '0.1'
# The full version, including alpha/beta/rc tags.
release = '0.1'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'cs'
