site_name: Dokumenty na úředních deskách
pages:
    - Obsah: index.md
    - Fyzická osoba: fyzickaOsoba.md
    - Místo: misto.md
    - Místo dle RÚIAN: ruian.md
    - Organizace: organizace.md
    - Oznámení na úřední desce: oznameni.md
    - Subjekt oznámení: subjekt.md
theme: readthedocs